### ISSUE TITLE
Malicious actors can swap without fees, via "exit"

### ISSUE THREAD

**Issue by alexcos20** [oceanprotocol/contracts#487]
Suppose that we have a pool DT1 <-> OCEAN  with 5% swap fee and spot price 1 DT = 100 OCEAN

There are two ways to swap OCEAN for DT.
1. swap 100 OCEAN to get 1 DT, ending up with 0.95 DT  (because he paid 5 Ocean fees). Or he pays roughly 105 OCEAN to get 1 DT.  Only one tx on chain. LPs are paid.
2. add OCEAN liquidity to the pool and then withdraw DT liquidity from the pool.  He will get 1 DT , but he has to spend gas for two transactions, and LPs are not getting any fees. (And exit fee is hardcoded in contracts, as EXIT_FEE=0.)

A malicious actor would choose (2), because no fees. 

Options
- A. have exit configurable by pool owner (EXIT_FEE). Then a Q: should OPC get a cut? Concern: increases code size, we're almost at the limit.
- B. have exit fee set to LP swap fee. Ensure OPC gets a cut too.
- C. only allow "exit" to be called if 0 stake. Therefore no fees would happen anyway, since 0 stake.
- D. only allow one-sided staking & unstaking (with OCEAN/H2O/etc). Do _not_ allow two-sided staking (DT + OCEAN/etc), unstaking (DT + OCEAN/etc) or exit (DT + OCEAN/etc) until one-sided staking bot turns off (ie all DTs minted).
- E. ignore

**Comment by trentmc** [comment]
My analysis.

- A and B are similar. B is better because simpler in code, and don't need yet one more parameter for users
- C solves the issue with one simple precondition at the top of the exit function. It drives behavior back to using the other functions. So C is better than B.
- E doesn't solve the problem. Given that C is so simple, I'd choose C over E.
- And what about D. This is interesting because it solves this issue, and a greater concern: I worry about other attacks that people might have arbitraging among two-sided staking, two-sided unstaking, or exit. We've seen one here, and we've seen a couple others in the last couple months. If we _only_ allow one-sided staking & unstaking until all DTs minted, it's much cleaner. 

Summary for me:
- it's either C or D
- C solves the current issue
- D solves the current issue, and shrinks the attack surface

Thoughts @alexcos20 ?

**Comment by alexcos20** [comment]
C - not sure what 0 stake means..
D  - unstaking = exit (remove liquidity from the pool). But it does not resolve the original issue.

**Comment by trentmc** [comment]
> C - not sure what 0 stake means..

Exit function can only be called by the actor if the actor has already called the remove-liquidity functions so that there's no liquidity left. 

> D - unstaking = exit (remove liquidity from the pool). But it does not resolve the original issue.

To clarify: I was under the impression that there are two separate functions: one "remove (2-sided) liquidity" and one "exit". Is this correct, or is there just one function "exit" that is the only way to remove (2-sided) liquidity?

**Comment by alexcos20** [comment]
Yes, there are 2 exit functions
 - exit with all pools token  (LP spends lp shares, gets all tokens).
 - exit with one token  (LP spends lp shares, but gets only one token)  (single side remove liquidity)

**Comment by trentmc** [comment]
> Yes, there are 2 exit functions
> 
> * exit with all pools token  (LP spends lp shares, gets all tokens). (in our case 2 sided)
> * exit with one token  (LP spends lp shares, but gets only one token)  (single side remove liquidity)

Thanks. So consider option D as: it only has single side remove liquidity. (And single side add liquidity. Until all DTs minted, ah which point single sided turns off and double sided turns on).

**Comment by alexcos20** [comment]
What about fees ?
Should we have exit fees on 
 - single side exit?
 - 2 side exit?  
 - both ?

**Comment by alexcos20** [comment]
also, note that exit fee is represented in pool shares.
So, if we have exit fees, we are are going to send pool shares to the fee address, not underlying tokens

**Comment by trentmc** [comment]
Let's get clear what option D proposes.

What it allows on the pool:
- stake OCEAN 
- unstake OCEAN (aka single sided exit)
- swap

What it does not allow (until all DTs minted)
- two sided staking
- two sided unstaking (aka two sided exit)

It does not charge fees on stake or unstake, just on swap. That's fine imo. (We discussed this before.)

Since it removes the path for the user to swap in a malicious / zero-fee way, it solves the problem of this github issue (until all DTs are minted). 

If we go with option D, we still have the Q: what about fees when all DTs are minted. I'd suggest: for simplicity, leave it as-is, since there was already a lot of monetization on the DT up to that point.

**Comment by alexcos20** [comment]
So we should not allow:
 - stake DT
 - unstake DT
 - 2 side staking
 - 2 side unstaking
 

until all DTs are minted ?

**Comment by trentmc** [comment]
> So we should not allow:
> 
> * stake DT
> * unstake DT
> * 2 side staking
> * 2 side unstaking
> 
> until all DTs are minted ?

That's option D, yes. We should consider this option.

What do you think? You're closer to the implementation.

**Comment by alexcos20** [comment]
How we define "all DTs are minted" ?
totalSupply = cap ?  Not sure if this works.

SSBot will mint & burn on the way

**Comment by trentmc** [comment]
> How we define "all DTs are minted" ? totalSupply = cap ? Not sure if this works.
> 
> SSBot will mint & burn on the way

Tbh I thought you would have details on that, as something that was implemented so far.

From your comment, I guess it's not! That's ok.

I need more clarity on current behavior then. Does 1ss bot just mint with infinite supply of DTs ? Or until some DT cap?

**Comment by alexcos20** [comment]
ssBot mints all cap into the ssBot Contract Address and uses that to add in the pool.  See https://github.com/oceanprotocol/contracts/blob/v4main_postaudit/contracts/pools/ssContracts/SideStaking.sol#L311-L330

But there is a small catch there.

Imagine that cap is 100 and totalSupply = 90.
If you want to add 10 Ocean , ssBot can add 10 DT.   But if you want to add 11 Ocean, ssBot will not add any liquidity, because it exceeds the cap.
So canStake function depends on the amount of DT required to be added in the pool.

In our case (join both side, exit only DT side), what value should be used for canStake?  1 wei it's enough ?
It's easy to check canStake function from those stake/unstake function.

**Comment by alexcos20** [comment]
what if we unlock those methods when pool DT reserve > DT cap/2 ?
Then there is enough liquidity in the pool

**Comment by alexcos20** [comment]
after a call with @trentmc , we agreed on:

Allow:
 - single side OCEAN stake/unstake
 - two side stake/unstake

Disallow:
 - single side DT stake/unstake
