### ISSUE TITLE
Possible DT vesting bug

### ISSUE THREAD

**Issue by trangnv** [oceanprotocol/contracts#491]
**Describe the bug**
1. As I understand, in order to get DT vested, 1ss contract has to be called
`oneSSContract.getVesting(DT.address)`, vesting_amount doesn’t get all at once, but several time
- I used TokenSpice with PublisherAgent creates DT with `cap = 1000, vested_amount = 100`
- `updateMinVestingPeriod` to 500 for experiment
- set `ss_DT_vested_blocks` (ssParams required to create pool) to 600
- Then call `oneSSContract.getVesting(DT.address)` when block number >= 600 multiple times to try to get all DT vested

2. The number of DT vested when getVesting function is not consistent
- Some times it gets 96.83 DT and throw `Integer overflow` error
- Some time it gets 96 DT, then 100 DT then no error

**To Reproduce**
Use TokenSPICE v4_vesting branch
https://github.com/tokenspice/tokenspice/tree/v4_vesting

@trentmc @alexcos20

**Comment by trentmc** [comment]
Thanks for the info.

It's a bit weird to have it where vesting only works if you follow <arbitrary rule x> on the value of the input number.

Vesting will be commonplace: it will be the "good default" for single data asset published to have vesting.
- Ocean Market will supports it directly soon enough. Soon, 1000s of publishers
- Data scientists using ocean.py will have vesting by default as well. Eg Algovera
- Teams Ocean smart contracts directly shouldn't have to deal with this weirdness. Eg DataUnion.app, DataX

So let's not dismiss this.

Rather: How do we make it so that users never have to think about this quirk? Ideally, we do a tweak at the smart contract level. cc @alexcos20

**Comment by alexcos20** [comment]
It's just math, there is nothing that we can do. But let's do some math:
 - publishers sets cap to 10.000.000 , vesting: 1.000.000 over 24 months.  Even if he withdraws every day, we have 730 function calls, which in worst case scenario, will lead to a loss of 730 WEI  (0.00000000000000073 DT)
 - publishers sets cap to 1.000.000 , vesting: 1.00.000 over 60 months.  Even if he withdraws 10 time per day, we have 18250 function calls, which in worst case scenario, will lead to a loss of 18250 WEI  (0.00000000000001825DT)

Values are neglectable.
@trentmc  @trangnv  ?

**Comment by trentmc** [comment]
Alright with me then.

We should document this for smart contract users.

Do we have a page with documentation on vesting? 
- If no, let's create a ticket for such documentation; then add a couple lines on this
- If yes, then let's add a couple lines

Then I'm fine to close this issue

**Comment by alexcos20** [comment]
Updated Readme in https://github.com/oceanprotocol/contracts/pull/556/commits/249c9b2d51c79a95dce5f427e33a1a648c4d8576
