### ISSUE TITLE
Gasless interactions

### ISSUE THREAD

**Issue by alexcos20** [oceanprotocol/contracts#688]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by trentmc** [comment]
This was only created in the event that we actually want to do this. There are other, simpler ways to solve the customer problem (faucet to users).

There was a discussion in: https://github.com/oceanprotocol/pm/issues/174

And from that, the approach assumed by this issue was not chosen. Therefore, closing this issue.
